const { execFile } = require('child_process');
const fs = require('fs');
const path = require('path');

const IMAGE = process.env.DEMO_IMAGE || 'ghcr.io/dumidusa/shipwright:latest';
const NETWORK = process.env.DOCKER_NETWORK || 'shipwright_default';
const NGINX_CONTAINER = process.env.NGINX_CONTAINER || 'shipwright-nginx-1';
const UPSTREAM_DIR = process.env.UPSTREAM_DIR || path.join(__dirname, '..');
const ACTIVE_FILE = path.join(UPSTREAM_DIR, 'active.conf');
const STATE_FILE = path.join(__dirname, '..', 'data', 'slot.json');

const SLOTS = {
  blue: { name: 'demo-blue', port: 4001 },
  green: { name: 'demo-green', port: 4002 },
};

function sh(cmd, args) {
  return new Promise((resolve, reject) => {
    execFile(cmd, args, { timeout: 30000 }, (err, stdout, stderr) => {
      if (err) return reject(new Error(stderr || err.message));
      resolve(stdout.trim());
    });
  });
}

function getActiveSlot() {
  try {
    const raw = fs.readFileSync(STATE_FILE, 'utf8');
    return JSON.parse(raw).active === 'green' ? 'green' : 'blue';
  } catch {
    return 'blue'; // default first-run slot
  }
}

function setActiveSlot(slot) {
  fs.mkdirSync(path.dirname(STATE_FILE), { recursive: true });
  fs.writeFileSync(STATE_FILE, JSON.stringify({ active: slot, updatedAt: new Date().toISOString() }));
}

async function pullImage(gitSha) {
  const tag = gitSha ? `${IMAGE.split(':')[0]}:${gitSha}` : IMAGE;
  await sh('docker', ['pull', tag]);
  return tag;
}

async function startContainer(slot, imageTag) {
  const { name, port } = SLOTS[slot];
  await sh('docker', ['rm', '-f', name]).catch(() => {});
  await sh('docker', [
    'run', '-d',
    '--name', name,
    '--network', NETWORK,
    '-p', `${port}:3000`,
    '--restart', 'unless-stopped',
    imageTag,
  ]);
}

async function stopContainer(slot) {
  const { name } = SLOTS[slot];
  await sh('docker', ['rm', '-f', name]).catch(() => {});
}

async function healthCheck(slot, { retries = 10, delayMs = 1000 } = {}) {
  const { name } = SLOTS[slot];
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(`http://${name}:3000/health`);
      if (res.ok) return true;
    } catch {
      // not ready yet, keep retrying
    }
    await new Promise((r) => setTimeout(r, delayMs));
  }
  return false;
}

function writeUpstreamConf(slot) {
  const { name } = SLOTS[slot];
  fs.mkdirSync(UPSTREAM_DIR, { recursive: true });
  const conf = `# auto-generated by deployer, do not edit by hand\nupstream app_upstream {\n    server ${name}:3000;\n}\n`;
  fs.writeFileSync(ACTIVE_FILE, conf);
}

async function reloadNginx() {
  await sh('docker', ['exec', NGINX_CONTAINER, 'nginx', '-s', 'reload']);
}

/**
 * Full rollout: deploy new version to the inactive slot, health check it,
 * swap nginx to point at it, then tear down the old slot.
 * Rolls back automatically if the health check fails.
 */
async function rollout(gitSha) {
  const currentSlot = getActiveSlot();
  const nextSlot = currentSlot === 'blue' ? 'green' : 'blue';

  const imageTag = await pullImage(gitSha);
  await startContainer(nextSlot, imageTag);

  const healthy = await healthCheck(nextSlot);
  if (!healthy) {
    await stopContainer(nextSlot);
    throw new Error(`health check failed for slot=${nextSlot}, rolled back (old slot=${currentSlot} untouched)`);
  }

  writeUpstreamConf(nextSlot);
  await reloadNginx();
  setActiveSlot(nextSlot);

  await new Promise((r) => setTimeout(r, 2000));
  await stopContainer(currentSlot);

  return { from: currentSlot, to: nextSlot, image: imageTag };
}

module.exports = { rollout, getActiveSlot };