worker_processes auto;

events{
    worker_connections 1024;
}
http{
    include /etc/nginx/upstream.d/active.conf;

    server{
        listen 80;

        location / {
            proxy_pass http://app_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_next_upstream error timeout http_502 http_503;
        }
    }
}